name: Build

on: [push]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [x86, x64]
    steps:
    - uses: actions/checkout@v2
  
  
    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        vs-version: '17.4.1'
        vs-prerelease: true

    # Install vcpkg
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat

    # Install vcpkg dependencies
    - name: Install vcpkg dependencies
      run: |
        cd vcpkg
        .\vcpkg install zydis:${{ matrix.platform }}-windows
        .\vcpkg integrate install

    # Build
    - name: Build Gancho
      run: |
        cd Gancho
        msbuizld Gancho.sln /p:Configuration=Release /p:Platform=${{ matrix.platform }}
